project:
  type: website

website:
  title: "Wei Wang's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  site-url: "https://vivwang-code.github.io/viviwang-code.github.io/"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



